# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fractality' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fractality

    pod 'FractalCore', :path => '/Users/admin/Documents/Projects/Fractality/FractalCore'
end
